"""Compile contracts -> generated artifacts.

Each artifact is produced by a pure ``render_*`` function so the same logic
powers both `anma sync` (write) and `anma sync --check` (drift detection in CI).
"""
from __future__ import annotations

import datetime as _dt
import re
import stat
from pathlib import Path

from . import templates as T
from .contracts import ModuleContract, Project

# Artifacts that are pure functions of the contracts and must never be hand-edited.
# These are the ones drift-checked by `anma sync --check`.
REGENERATED = "regenerated"
# Artifacts seeded once and then owned by the user (not drift-checked).
SEED_ONCE = "seed_once"


# --------------------------------------------------------------------------- #
# pure renderers                                                              #
# --------------------------------------------------------------------------- #
def _dep_import_paths(project: Project, m: ModuleContract) -> list[str]:
    names = project.by_name()
    return [names[d].import_path for d in m.depends_on if d in names]


def render_tach_toml(project: Project) -> str:
    roots = ", ".join(f'"{r}"' for r in project.source_roots)
    lines = [f"source_roots = [{roots}]", ""]
    for m in project.modules:
        lines.append("[[modules]]")
        lines.append(f'path = "{m.import_path}"')
        deps = ", ".join(f'"{d}"' for d in _dep_import_paths(project, m))
        lines.append(f"depends_on = [{deps}]")
        if m.public:
            members = ", ".join(f'"{p}"' for p in m.public)
            lines.append("[[interfaces]]")
            lines.append(f"expose = [{members}]")
            lines.append(f'from = ["{m.import_path}"]')
        lines.append("")
    return "\n".join(lines)


def render_map_block(project: Project) -> str:
    rows = []
    for m in sorted(project.modules, key=lambda x: x.name):
        uses = ", ".join(m.depends_on) if m.depends_on else "(nothing)"
        rows.append(f"- **{m.name}** — {m.summary}  \n  uses: {uses}")
    return T.ROOT_MAP.format(start=T.MAP_START, end=T.MAP_END, rows="\n".join(rows))


def render_module_claude(m: ModuleContract) -> str:
    public = "\n".join(f"- `{p}`" for p in m.public) or "- (none declared yet)"
    invariants = "\n".join(f"- {i}" for i in m.invariants) or "- (none declared)"
    depends = ", ".join(m.depends_on) if m.depends_on else "nothing"
    return T.MODULE_CLAUDE.format(
        name=m.name, summary=m.summary or "(no summary)",
        public=public, depends=depends, invariants=invariants)


def render_codeowners(project: Project) -> str | None:
    owned = [m for m in project.modules if m.owners]
    if not owned:
        return None
    lines = ["# Generated by `anma sync` from each module's `owners` field.", ""]
    for m in sorted(owned, key=lambda x: x.name):
        rel = m.path.relative_to(project.root).as_posix()
        lines.append(f"/{rel}/ {' '.join(m.owners)}")
    return "\n".join(lines) + "\n"


def render_ci(project: Project) -> str:
    return T.CI_WORKFLOW.format(py=project.python_version)


def _merge_root_claude(project: Project, existing: str | None) -> str:
    block = render_map_block(project)
    if existing is None:
        return f"# {project.root.name}\n\n{block}\n"
    if T.MAP_START in existing:
        pat = re.compile(re.escape(T.MAP_START) + r".*?" + re.escape(T.MAP_END), re.S)
        return pat.sub(block, existing)
    return existing.rstrip() + "\n\n" + block + "\n"


# --------------------------------------------------------------------------- #
# the regenerated plan (path -> content). Used by both sync and drift-check.   #
# --------------------------------------------------------------------------- #
def regenerated_plan(project: Project) -> dict[Path, str]:
    root = project.root
    plan: dict[Path, str] = {
        root / "tach.toml": render_tach_toml(project),
        root / ".claude" / "rules" / "boundaries.md": T.BOUNDARIES_RULE,
        root / ".claude" / "hooks" / "anma_pretooluse.py": T.PRETOOLUSE_HOOK,
        root / ".github" / "workflows" / "anma.yml": render_ci(project),
    }
    for m in project.modules:
        plan[m.path / "CLAUDE.md"] = render_module_claude(m)
    co = render_codeowners(project)
    if co is not None:
        plan[root / ".github" / "CODEOWNERS"] = co
    return plan


def _w(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def sync(project: Project) -> list[str]:
    """Regenerate every artifact from the contracts. Returns paths written."""
    written: list[str] = []

    for path, content in regenerated_plan(project).items():
        _w(path, content)
        if path.name == "anma_pretooluse.py":
            path.chmod(path.stat().st_mode | stat.S_IEXEC)
        written.append(str(path))

    # root CLAUDE.md: merge generated map into any user prose.
    root_claude = project.root / "CLAUDE.md"
    existing = root_claude.read_text() if root_claude.exists() else None
    _w(root_claude, _merge_root_claude(project, existing))
    written.append(str(root_claude))

    # seed-once files (never clobbered, never drift-checked)
    for path, content in _seed_once(project).items():
        if not path.exists():
            _w(path, content)
            written.append(str(path))
    return written


def _seed_once(project: Project) -> dict[Path, str]:
    today = _dt.date.today().isoformat()
    return {
        project.root / ".claude" / "settings.json": T.SETTINGS_JSON.format(),
        project.root / ".pre-commit-config.yaml": T.PRECOMMIT,
        project.root / "DECISIONS.md": T.DECISIONS_SEED.format(date=today),
    }


def check_drift(project: Project) -> list[str]:
    """Return a list of artifacts that are stale vs the contracts (empty = clean)."""
    stale: list[str] = []
    for path, expected in regenerated_plan(project).items():
        actual = path.read_text() if path.exists() else None
        if actual != expected:
            rel = path.relative_to(project.root)
            stale.append(f"{rel} ({'missing' if actual is None else 'out of date'})")

    # root CLAUDE.md: only the generated map block must match.
    root_claude = project.root / "CLAUDE.md"
    existing = root_claude.read_text() if root_claude.exists() else None
    expected_block = render_map_block(project)
    block = ""
    if existing and T.MAP_START in existing:
        m = re.search(re.escape(T.MAP_START) + r".*?" + re.escape(T.MAP_END), existing, re.S)
        block = m.group(0) if m else ""
    if block != expected_block:
        stale.append("CLAUDE.md (architecture map out of date)")
    return stale
