"""String templates for everything ANMA generates from contracts."""
from __future__ import annotations

MAP_START = "<!-- ANMA:MAP:START -->"
MAP_END = "<!-- ANMA:MAP:END -->"

# Root CLAUDE.md map block. Lives between markers so any prose you write around
# it is preserved across `anma sync`.
ROOT_MAP = """{start}
## Architecture map (generated by `anma sync` — do not edit by hand)

This project uses ANMA contracts. **Respect these module boundaries.** A module
may only import from modules listed under "uses". Going outside that is blocked
by a pre-commit hook and CI.

{rows}

**Rules**
- Import other modules only through their public interface (listed in each
  module's own `CLAUDE.md`). Do not reach into a module's internals.
- If you need a dependency that isn't allowed, do not add the import. Update the
  source module's `anma.yaml` (`depends_on`), run `anma sync`, and record why in
  `DECISIONS.md` — then the boundary is real and persists to the next session.
- Run `anma check` before committing. It also runs in CI.
{end}"""

MODULE_CLAUDE = """<!-- Generated by `anma sync` from anma.yaml. Edit the contract, not this file. -->
# Module: {name}

{summary}

**Public interface** (the only surface other modules may import):
{public}

**May import:** {depends}

**Invariants** (do not violate):
{invariants}

If a change here would break the public interface or these invariants, stop and
flag it — other modules and parallel agents depend on this contract.
"""

BOUNDARIES_RULE = """<!-- Generated by `anma sync`. -->
# Module boundaries (ANMA)

IMPORTANT: This repo enforces module boundaries. Before adding any import
between modules, confirm it is allowed in the source module's `anma.yaml`
(`depends_on`). Cross-module access must go through the target module's public
interface — never its internals.

To change a boundary: edit the module's `anma.yaml`, run `anma sync`, and add a
one-line entry to `DECISIONS.md`. Do not work around the boundary in code.

Verify with: `anma check`
"""

# PreToolUse hook: blocks an edit that would introduce a boundary violation.
# Claude Code blocks the tool call when the hook exits with code 2.
PRETOOLUSE_HOOK = '''#!/usr/bin/env python3
"""ANMA PreToolUse hook. Exit code 2 blocks the tool call (Claude Code convention)."""
import json
import subprocess
import sys

def main() -> int:
    try:
        json.load(sys.stdin)  # tool payload; we re-check the whole project, fast.
    except Exception:
        pass
    proc = subprocess.run(["anma", "check", "--quiet"], capture_output=True, text=True)
    if proc.returncode != 0:
        sys.stderr.write(
            "ANMA: this edit breaks a module boundary.\\n"
            + proc.stdout
            + "\\nFix the import, or update the module's anma.yaml + run `anma sync` "
            "and note it in DECISIONS.md.\\n"
        )
        return 2  # block
    return 0

if __name__ == "__main__":
    sys.exit(main())
'''

SETTINGS_JSON = """{{
  "hooks": {{
    "PreToolUse": [
      {{
        "matcher": "Edit|Write|MultiEdit",
        "hooks": [
          {{ "type": "command", "command": "python3 .claude/hooks/anma_pretooluse.py" }}
        ]
      }}
    ]
  }}
}}"""

CI_WORKFLOW = """# Generated by `anma sync`.
name: anma
on: [push, pull_request]
jobs:
  boundaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {{ python-version: "{py}" }}
      - run: pip install anma[tach]
      - run: anma sync --check   # fail if generated docs/config drifted from contracts
      - run: anma check          # enforce module boundaries
"""

PRECOMMIT = """# Generated by `anma sync`.
repos:
  - repo: local
    hooks:
      - id: anma-check
        name: anma check (module boundaries)
        entry: anma check
        language: system
        pass_filenames: false
"""

DECISIONS_SEED = """# Architecture decisions (ANMA)

Append-only. Each entry explains *why* a boundary is the way it is, so neither
you nor Claude relitigates it next session. Newest on top.

## {date} — Adopted ANMA contracts
Module boundaries are now declared in per-module `anma.yaml` files and enforced
by `anma check` (pre-commit + CI + Claude Code PreToolUse hook).
"""
